# Funding options for Beaconchain Horizon

github: [beaconchain-com]
custom: ['https://beaconchain.us/donate']

# حذف شده به دلیل عدم وجود حساب فعال:
# patreon: 
# open_collective: 
# ko_fi: 
# tidelift: 
# community_bridge: 
# liberapay: 
# issuehunt: 
# otechie:
